-- +goose Up
ALTER TABLE ideas
ADD CONSTRAINT fk_ideas
FOREIGN KEY (teamid)
REFERENCES teams(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE projects
ADD CONSTRAINT fk_projects
FOREIGN KEY (teamid)
REFERENCES teams(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE users
ADD CONSTRAINT fk_teams
FOREIGN KEY (team_id)
REFERENCES teams(id)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE vit_details
ADD CONSTRAINT fk_details
FOREIGN KEY (user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- +goose Down
ALTER TABLE ideas
DROP CONSTRAINT fk_ideas;

ALTER TABLE projects
DROP CONSTRAINT fk_projects;

ALTER TABLE users
DROP CONSTRAINT fk_teams;

ALTER TABLE vit_details
DROP CONSTRAINT fk_details;
