-- +goose Up
ALTER TABLE teams
ADD CONSTRAINT fk_ideas
FOREIGN KEY (ideaid)
REFERENCES ideas(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE teams
ADD CONSTRAINT fk_projects
FOREIGN KEY (projectid)
REFERENCES projects(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE users
ADD CONSTRAINT fk_teams
FOREIGN KEY (team_id)
REFERENCES teams(id)
ON UPDATE CASCADE;

-- +goose Down
ALTER TABLE teams
DROP CONSTRAINT fk_ideas, 
DROP CONSTRAINT fk_projects;

ALTER TABLE users
DROP CONSTRAINT fk_teams;